version: "2"
services:
  mytardis-base:
    build:
      context: mytardis
      dockerfile: Dockerfile-base
    image: mytardis/mytardis-base
  mytardis:
    build:
      context: .
      dockerfile: Dockerfile-mytardis
    image: mytardis/mytardis