FROM ubuntu:18.04

# Installing basic dependancies
ENV DEBIAN_FRONTEND noninteractive
RUN echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90assumeyes
RUN apt-get update && apt-get install \
    -qy \
    -o APT::Install-Recommends=false \
    -o APT::Install-Suggests=false \
    openssh-server

RUN groupadd -r staging && useradd -r -g staging staging
RUN mkdir -p /home/staging/.ssh
RUN chown -R staging:staging /home/staging
COPY --chown=staging:staging authorized_keys /home/staging/.ssh
RUN chmod -R 500 /home/staging/.ssh

CMD /etc/init.d/ssh start && tail -f /dev/null
