version: "3.6"

x-project-image:
  &project-image
  imagetrove/mytardis:latest

services:
  redis:
    image: redis
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3-management

  mytardis:
    image: *project-image
    links:
      - rabbit
    depends_on:
      - rabbit
      - redis
    command: bash -c "/home/app/env/bin/gunicorn -c gunicorn_settings.py -b unix:/tmp/gnicorn.socket -b 0.0.0.0:8000 wsgi:application"
    # command: bash -c "source ~/env/bin/activate; python manage.py runserver 0.0.0.0:8000"

  celery:
    image: *project-image
    depends_on:
      - rabbit
    command: bash -c 'sleep 10; export DJANGO_SETTINGS_MODULE=tardis.settings; /home/app/env/bin/celery worker -A tardis.celery.tardis_app -c 2 -Q celery,default -n \"allqueues.%%h\"'

  beat:
    image: *project-image
    depends_on:
      - rabbit
    command: bash -c 'sleep 10; export DJANGO_SETTINGS_MODULE=tardis.settings; /home/app/env/bin/celery beat -A tardis.celery.tardis_app --loglevel INFO'

  staging:
    image: imagetrove/staging:latest

# source ~/env/bin/activate
# python mytardis.py migrate --noinput
# python mytardis.py createcachetable default_cache; python mytardis.py createcachetable celery_lock_cache
# python mytardis.py collectstatic --no-input
# python mytardis.py createsuperuser
# python mytardis.py rebuild_index
# python mytardis.py shell_plus
