FROM ubuntu:18.04

RUN groupadd -r webapp && useradd -r -g webapp webapp

COPY mytardis /home/webapp/

RUN chown -R webapp:webapp /home/webapp
WORKDIR /home/webapp

RUN mkdir /appenv
RUN chown -R webapp:webapp /appenv

ENV DEBIAN_FRONTEND noninteractive
RUN echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update && apt-get install \
    -qy \
    -o APT::Install-Recommends=false \
    -o APT::Install-Suggests=false \
    curl \
    sudo \
    && apt-get upgrade \
    && apt-get autoremove \
    && apt-get clean

RUN bash install-ubuntu-requirements.sh

USER webapp
RUN virtualenv --system-site-packages /appenv

RUN . /appenv/bin/activate; pip install -U pip
RUN . /appenv/bin/activate; pip install -r requirements.txt
RUN . /appenv/bin/activate; pip install psycopg2-binary

RUN npm install --production

