version: "3"
services:
  mytardis-base:
    build:
      context: .
      dockerfile: Dockerfile-base
    image: imagetrove/mytardis-base
  mytardis-run:
    build:
      context: .
      dockerfile: Dockerfile-run
    network_mode: "host"
    image: imagetrove/mytardis-run

    # depends_on:
      # - migration
  # migration:
    # image: imagetrove/mytardis-run
    # command: bash -c "source /appenv/bin/activate; python mytardis.py migrate"
