version: "3.6"

# x-project-mount:
#   &project-mount
#     - ../store:/store
#     - ../logs:/home/app/logs
#     - ../static:/home/app/static
#     - ./settings.py:/home/app/src/tardis/settings.py
#     - ./monash_openid_login:/home/app/src/monash_openid_login

# x-project-image:
#   &project-image
#   imagetrove/mytardis:latest


# services:
#   bash:
#     image: *project-image
#     volumes: *project-mount
#     command: bash -c "source ~/env/bin/activate; bash"

  # migrate:
  #   extends:
  #     file: docker-compose.yml
  #     service: mytardis
  #   command: /bin/bash -c "source ~/env/bin/activate; python mytardis.py migrate --noinput"

  # createcachetable:
  #   extends:
  #     file: docker-compose.yml
  #     service: mytardis
  #   command: /bin/bash -c "source ~/env/bin/activate; python mytardis.py createcachetable default_cache; python mytardis.py createcachetable celery_lock_cache"

  # collectstatic:
  #   extends:
  #     file: docker-compose.yml
  #     service: mytardis
  #   command: /bin/bash -c "source ~/env/bin/activate; python mytardis.py collectstatic --no-input"

  # createsuperuser:
  #   extends:
  #     file: docker-compose.yml
  #     service: mytardis
  #   command: /bin/bash -c "source ~/env/bin/activate; python mytardis.py createsuperuser"

  # rebuild_index:
  #   extends:
  #     file: docker-compose.yml
  #     service: mytardis
  #   command: /bin/bash -c "source ~/env/bin/activate; python mytardis.py rebuild_index"

  # shell_plus:
  #   extends:
  #     file: docker-compose.yml
  #     service: mytardis
  #   volumes:
  #   - ./shell_run.py:/home/webapp/shell_run.py
  #   command: /bin/bash -c "source ~/env/bin/activate; python mytardis.py shell_plus"

  # bash:
  #   extends:
  #     file: docker-compose.yml
  #     service: mytardis
  #   command: /bin/bash -c "source ~/env/bin/activate; bash"
